[default.general]
chip = "STM32F446RE"

[default.rtt]
enabled = true

[default.gdb]
enabled = false

[default.reset]
halt_afterwards = false

[profile.release]
debug = false
lto = true
opt-level = "s"
